name: Discord Changelog Notification

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification via Embed
        uses: actions/github-script@v7
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          script: |
            const repoName = process.env.GITHUB_REPOSITORY;
            const repoUrl = `https://github.com/${repoName}`;
            const commits = context.payload.commits;

            const fields = commits.map(commit => {
              const shortSha = commit.id.substring(0, 7);
              const commitUrl = commit.url;
              const messageLines = commit.message.split('\n');
              const title = messageLines[0];
              const body = messageLines.slice(1).join('\n').trim();
            
              return {
                name: '\u200B',  // Zero-width space to omit the field title
                value: `[\`${shortSha}\`](${commitUrl}) - **${title}**\n${body || ''}`
              };
            });

            const payload = {
              embeds: [
                {
                  title: `Push to ${repoName}`,
                  url: repoUrl,
                  fields: fields,
                  color: 0x7289DA,
                  timestamp: new Date().toISOString()
                }
              ]
            };

            await fetch(process.env.DISCORD_WEBHOOK_URL, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(payload)
            });

