name: Discord Changelog Notification

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        uses: actions/github-script@v7
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          script: |
            const repoName = process.env.GITHUB_REPOSITORY;
            const repoUrl = `https://github.com/${repoName}`;
            const commits = context.payload.commits;

            let message = `**[${repoName}](${repoUrl}) - Push Notification**\n\n`;

            for (const commit of commits) {
              const shortSha = commit.id.substring(0, 7);
              message += `*[\\\`${shortSha}\\`](<${commit.url}>)* - ${commit.message} (\`${commit.author.name}\`)\n`;
            }

            await fetch(process.env.DISCORD_WEBHOOK_URL, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ content: message })
            });
